name: Scheduled deploy

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: npm ci
      - run: npm run build
      - run: |
          npm install --save-dev firebase-tools
          ./node_modules/.bin/firebase use ${{ secrets.FIREBASE_PROJECT_ID }}
          ./node_modules/.bin/firebase deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_CLI_EXPERIMENTS: webframeworks
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.FIREBASE_KEY }}
